---
title: "NMF Pipeline"
author: "Lucie Chrastecka"
date: "8/30/2021"
output: html_document
editor_options: ]
  chunk_output_type: console
---

LIBRARY
```{r}
#PACKAGES
library(msigdbr)
library(gplots)
library(ggplot2)
library(heatmap.plus)
library(RColorBrewer)
library(biomaRt)
library(wesanderson)
library(readr)
library(FactoMineR)
library(readr)
library(factoextra)
library(dplyr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(gridExtra)
library(DESeq2)
library(data.table)
library(pdist)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library(qusage)


```


DATA
```{r}

full_Snyder <- ODIS::full_Snyder
full_Snyder$ex <- as.matrix(full_Snyder$ex)
snyder_readcounts <- full_Snyder$ex

```


MOUSE ENSEMBL TO MOUSE ENTREZ GENE CONVERSION + MGI SYMBOL
# ```{r}
# 
# SnyderMouseGenes <- full_Snyder$featInfo$ENSEMBL
# tmp_snyder <- Mouse2Human(SnyderMouseGenes) #need human homologue to run gsea
# head(tmp_snyder)
# #tmp_snyder <- lapply(tmp_snyder,as.character)
# summary(tmp_snyder)
# head(tmp_snyder)
# str(tmp_snyder)
# tmp_snyder <- as.data.frame(tmp_snyder)
# 
# full_Snyder$featInfo <- as.data.frame(full_Snyder$featInfo)
# full_Snyder$featInfo <- merge(full_Snyder$featInfo, tmp_snyder)
# summary(full_Snyder$featInfo)
# head(full_Snyder$featInfo)
# ```

```{r}

SnyderMouseGenes <- full_Snyder$featInfo$ENSEMBL
tmp_snyder <- ODIS::MouseENS2MouseENT(SnyderMouseGenes)
head(tmp_snyder)
#tmp_snyder <- lapply(tmp_snyder,as.character)
summary(tmp_snyder)
head(tmp_snyder)
str(tmp_snyder)
tmp_snyder <- as.data.frame(tmp_snyder)

full_Snyder$featInfo <- as.data.frame(full_Snyder$featInfo)
full_Snyder$featInfo <- merge(full_Snyder$featInfo, tmp_snyder)
summary(full_Snyder$featInfo)
head(full_Snyder$featInfo)
```

Only Organoids
```{r}
#TRIMMING ONLY ORGANOIDS
idx = which(full_Snyder$sampInfo$tissue == "organoid")
snyder_readcounts_org = full_Snyder$ex[,idx]
str(snyder_readcounts_org)
head(snyder_readcounts_org)

snyder_samps_org = full_Snyder$sampInfo[idx,]
str(snyder_samps_org)
head(snyder_samps_org)

#rownames(snyder_readcounts_org) = make.names(rownames(snyder_readcounts_org), unique=TRUE)


```

NMF only Organoids
```{r}
snyder_readcounts_org <- as.data.frame(snyder_readcounts_org)
snyder_readcounts_org <- tibble::rownames_to_column(snyder_readcounts_org, "ENSEMBL")
snyder_readcounts_org <- plyr::join(snyder_readcounts_org, full_Snyder$featInfo)
my_entrez_readcounts_org <- snyder_readcounts_org[,c(2:10)]
my_entrez_readcounts_org$ENTREZ <- as.character(my_entrez_readcounts_org$ENTREZID)
my_entrez_readcounts_org <- my_entrez_readcounts_org[,c(-9)]
head(my_entrez_readcounts_org)

my_entrez_readcounts_org <- aggregate(x=my_entrez_readcounts_org[,-which(colnames(my_entrez_readcounts_org) == "ENTREZ")],
                                  by = list(ENTREZ= my_entrez_readcounts_org$ENTREZ),
                                  FUN = sum)


non_zero_matrix_org <- my_entrez_readcounts_org
non_zero_matrix_org <- data.frame(non_zero_matrix_org[,-1], row.names = non_zero_matrix_org[,1])
non_zero_matrix_org <- as.matrix(non_zero_matrix_org)
non_zero_matrix_org[non_zero_matrix_org<1] <- 0.1; non_zero_matrix_org

head(non_zero_matrix_org)


library(NMF)

set.seed(1234)
snyder_nmf_org <- nmf(x = non_zero_matrix_org, rank = 3, method = 'brunet') # if not transposed, runs mmediately, then just take non-trasposed h matrix

w_org <- t(coef(snyder_nmf_org))
dim(w_org)
head(w_org)

h_org <- basis(snyder_nmf_org)
dim(h_org)
head(h_org)

saveRDS(h_org, "./Snyder_NMF_org.rds")


```

NMF
```{r}
snyder_readcounts <- as.data.frame(snyder_readcounts)
snyder_readcounts <- tibble::rownames_to_column(snyder_readcounts, "ENSEMBL")
snyder_readcounts <- plyr::join(snyder_readcounts, full_Snyder$featInfo)
my_entrez_readcounts <- snyder_readcounts[,c(2:30)]
my_entrez_readcounts$ENTREZ <- as.character(my_entrez_readcounts$ENTREZID)
my_entrez_readcounts <- my_entrez_readcounts[,-(29)]
head(my_entrez_readcounts)

my_entrez_readcounts <- aggregate(x=my_entrez_readcounts[,-which(colnames(my_entrez_readcounts) == "ENTREZ")],
                                  by = list(ENTREZ= my_entrez_readcounts$ENTREZ),
                                  FUN = sum)


non_zero_matrix <- my_entrez_readcounts
non_zero_matrix <- data.frame(non_zero_matrix[,-1], row.names = non_zero_matrix[,1])
non_zero_matrix <- as.matrix(non_zero_matrix)
non_zero_matrix[non_zero_matrix<1] <- 0.1; non_zero_matrix

head(non_zero_matrix)


library(NMF)

set.seed(1234)
snyder_nmf <- nmf(x = non_zero_matrix, rank = 3, method = 'brunet') # if not transposed, runs mmediately, then just take non-trasposed h matrix

w <- t(coef(snyder_nmf))
dim(w)
head(w)

h <- basis(snyder_nmf)
dim(h)
head(h)

saveRDS(h, "./Snyder_NMF.rds")


```

Make GSEA friendly "gene_list"
```{r}
Snyder_NMF <- readRDS("./Snyder_NMF.rds")
head(Snyder_NMF)
Snyder_NMF_org <- readRDS("./Snyder_NMF_org.rds")
head(Snyder_NMF_org)

library(BBmisc)
nmf_norm <- normalize(Snyder_NMF, method = "range", range = c(0, 1), margin = 1L, on.constant = "quiet")
head(nmf_norm)
df1 <- nmf_norm[,1]
head(df1)

nmf_norm_org <- normalize(Snyder_NMF_org, method = "range", range = c(0, 1), margin = 1L, on.constant = "quiet")
head(nmf_norm_org)
df2 <- nmf_norm_org[,1]
head(df2)
```


ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}

C1_df = msigdbr(species = "Mus musculus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Mus musculus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Mus musculus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Mus musculus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Mus musculus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Mus musculus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Mus musculus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df)

list_of_gmt_files <- ODIS::convert_msigdbr_obj_to_gmt_file(list_of_sets)
```


NMF GSEA, done separately on norm. and norm_org
```{r}

gene_list <- df2
head(gene_list, n = 5)

gene_list = sort(gene_list, decreasing = TRUE)
gene_list = gene_list[!duplicated(names(gene_list))]
head(gene_list, n = 5)

for(i in list_of_gmt_files){
  print(i)
  res_org <- ODIS::ODISGSEA(gene_list = gene_list, theGoFile = i, pval = 0.05) ## need to structure outputs correctly
}


summary(res)
summary(res_org)
saveRDS(res, "./Snyder_NMF_res.rds")
saveRDS(res_org, "./Snyder_NMF_res_org.rds")
```

Gsea on both nmf all and org in one for loops
```{r}

snyder_nmfs <- list()

for(Y in list("norm" = nmf_norm,
              "norm_org" = nmf_norm_org)
){
  gene_list <- Y[,1]
  
  gene_list = sort(gene_list, decreasing = TRUE)
  gene_list = gene_list[!duplicated(names(gene_list))]
  head(gene_list, n = 5)
  
  for(i in list_of_gmt_files){
    print(i)
    res <- ODIS::ODISGSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    snyder_nmfs[row.names(Y)][[i]] <- res  ## find a way to reference "nmf_norm" and "nmf_norm_org"
  }
  snyder_nmfs[row.names(Y)]$orig_matrix <- row.names(Y) ##find a way to create "orig matrix" object with NMF output
}

saveRDS(res, "./Snyder_NMF_both.rds")
#res both is the same as res_org, need to structure output correctly it where its fucking up



```

GENE VS GENE SET HEATMAPS
```{r}
ODIS::ODIS.Heatmaps(res)
```
