---
title: "NMF_Test"
author: "Lucie Chrastecka"
date: "3/12/2021"
output: html_document
---


Data
```{r}
load("rank3_ibd_lucie.RData")
x <- as.data.frame(rank3_ibd_lucie)
x <- tibble::rownames_to_column(x, "genes")
head(x)

C1_df = msigdbr(species = "Homo sapiens", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Homo sapiens", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Homo sapiens", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Homo sapiens", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Homo sapiens", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Homo sapiens", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Homo sapiens", category = "C7", subcategory = "")
C8_df = msigdbr(species = "Homo sapiens", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df)

list_of_human_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)

```

GSEA
```{r}
#note to self: remember to source the Lucie_GSEA function here dumbass


outputs_NMF_V1 <- list()
outputs_NMF_V2 <- list()
outputs_NMF_V3 <- list()

#V1
  p <- x$V1
  entrezid <- x$genes
  
  gene_list <- (1 - p) *sign(p) 
  names(gene_list) <- as.character(entrezid)
  
  gene_list = sort(gene_list, decreasing = TRUE)
  gene_list = gene_list[!duplicated(names(gene_list))]
  head(gene_list, n = 5)
  
  for(i in list_of_human_gmt_files){
    print(i)
    res <- GSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    outputs_NMF_V1[i] <- res
  }
  
#V2
  p <- x$V2
  entrezid <- x$genes
  
  gene_list <- (1 - p) *sign(p) 
  names(gene_list) <- as.character(entrezid)
  
  gene_list = sort(gene_list, decreasing = TRUE)
  gene_list = gene_list[!duplicated(names(gene_list))]
  head(gene_list, n = 5)
  
  for(i in list_of_human_gmt_files){
    print(i)
    res <- GSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    outputs_NMF_V2[i] <- res
  }  
  
#V3
  p <- x$V3
  entrezid <- x$genes
  
  gene_list <- (1 - p) *sign(p) 
  names(gene_list) <- as.character(entrezid)
  
  gene_list = sort(gene_list, decreasing = TRUE)
  gene_list = gene_list[!duplicated(names(gene_list))]
  head(gene_list, n = 5)
  
  for(i in list_of_human_gmt_files){
    print(i)
    res <- GSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    outputs_NMF_V3[i] <- res
  }  

```

Saving Data Neatly
```{r}
saveRDS(outputs_NMF_V1, "./outputs_NMF_V1.rds")
saveRDS(outputs_NMF_V2, "./outputs_NMF_V2.rds")
saveRDS(outputs_NMF_V3, "./outputs_NMF_V3.rds")
```



