---
title: "Snyder Pipeline"
author: "Lucie Chrastecka"
date: "1/18/2021"
output: html_document
editor_options: ]
  chunk_output_type: console
---

LIBRARY
```{r}
#PACKAGES
library(msigdbr)
library(gplots)
library(ggplot2)
library(heatmap.plus)
library(RColorBrewer)
library(biomaRt)
library(wesanderson)
library(readr)
library(FactoMineR)
library(readr)
library(factoextra)
library(dplyr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(gridExtra)
library(DESeq2)
library(data.table)
library(pdist)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library(qusage)
```


DATA
```{r}

full_Snyder <- ODIS::full_Snyder
full_Snyder$ex <- as.matrix(full_Snyder$ex)
snyder_readcounts <- full_Snyder$ex

row.names(snyder_readcounts) <- full_Snyder$featInfo$ENSEMBL

```


MOUSE ENSEMBL TO MOUSE ENTREZ GENE CONVERSION + MGI SYMBOL
```{r}

SnyderMouseGenes <- full_Snyder$featInfo$ENSEMBL
tmp_snyder <- ODIS::MouseENS2MouseENT(SnyderMouseGenes)
head(tmp_snyder)
#tmp_snyder <- lapply(tmp_snyder,as.character)
summary(tmp_snyder)
head(tmp_snyder)
str(tmp_snyder)
tmp_snyder <- as.data.frame(tmp_snyder)

full_Snyder$featInfo <- as.data.frame(full_Snyder$featInfo)
full_Snyder$featInfo <- merge(full_Snyder$featInfo, tmp_snyder)
summary(full_Snyder$featInfo)
head(full_Snyder$featInfo)
```


#DESEQ2 
```{r}

deseq_2 <- ODIS::runDESeq2_indFilterActive(snyder_readcounts, full_Snyder$sampInfo$`hnf4a status`)
print(summary(deseq_2))
df1 <- as.data.frame(deseq_2$test)
df1 <- df1[-c(0, 1, 3:4, 6)]
df1 <- tibble::rownames_to_column(df1, "GeneID")
colnames(df1)[3] <- "deseq2"

deseq_2_cooks_off <- runDESeq2_indFilterDeactiveCooksOff(snyder_readcounts, full_Snyder$sampInfo$`hnf4a status`)
print(summary(deseq_2_cooks_off))
df2 <- as.data.frame(deseq_2_cooks_off$test)
df2 <- df2[-c(0, 1:4)]
df2 <- df2[-c(0, 2)]
df2 <- tibble::rownames_to_column(df2, "GeneID")
colnames(df2)[2] <- "deseq2 cooks off"


#ALL Snyder_DESEQ SUMMARY TABLE

Snyder_DESEQ <- merge(df1, df2, by = "GeneID")
names(Snyder_DESEQ)[names(Snyder_DESEQ)=="GeneID"] <- "ENSEMBL"
Snyder_DESEQ <- merge(Snyder_DESEQ, full_Snyder$featInfo)
head(Snyder_DESEQ)

saveRDS(Snyder_DESEQ, "./Snyder_DESEQ.rds")
#REPEAT FOR OTHER DE METHODS AND BUILD A MATRIX
#RIGHT NOW I ONLY HAVE DESEQ BUT IN THE FUTURE MATRIX WILL HAVE ALL DE METHODS NOT JUST DESEQ
```


#DESEQ2 ONLY ORGANOIDS
```{r}

#TRIMMING ONLY ORGANOIDS
idx = which(full_Snyder$sampInfo$tissue == "organoid")
snyder_readcounts_org = full_Snyder$ex[,idx]
str(snyder_readcounts_org)
head(snyder_readcounts_org)

snyder_samps_org = full_Snyder$sampInfo[idx,]
str(snyder_samps_org)
head(snyder_samps_org)

rownames(snyder_readcounts_org) = make.names(rownames(snyder_readcounts_org), unique=TRUE)


#DESEQ2

deseq_2 <- ODIS::runDESeq2_indFilterActive(snyder_readcounts_org, snyder_samps_org$`hnf4a status`)
print(summary(deseq_2))
df1 <- as.data.frame(deseq_2$test)
df1 <- df1[-c(0, 1, 3:4, 6)]
df1 <- tibble::rownames_to_column(df1, "GeneID")
colnames(df1)[3] <- "deseq2"

deseq_2_cooks_off <- runDESeq2_indFilterDeactiveCooksOff(snyder_readcounts_org, snyder_samps_org$`hnf4a status`)
print(summary(deseq_2_cooks_off))
df2 <- as.data.frame(deseq_2_cooks_off$test)
df2 <- df2[-c(0, 1:4)]
df2 <- df2[-c(0, 2)]
df2 <- tibble::rownames_to_column(df2, "GeneID")
colnames(df2)[2] <- "deseq2 cooks off"

#ALL Snyder_DESEQ_org SUMMARY TABLE

Snyder_DESEQ_org <- merge(df1, df2, by = "GeneID")
names(Snyder_DESEQ_org)[names(Snyder_DESEQ_org)=="GeneID"] <- "ENSEMBL"
Snyder_DESEQ_org <- merge(Snyder_DESEQ_org, full_Snyder$featInfo)
head(Snyder_DESEQ_org)

saveRDS(Snyder_DESEQ_org, "./Snyder_DESEQ_org.rds")
```


LOADING IN MATRIXES
```{r}

Snyder_DESEQ_ORG_matrix <- readRDS("./Snyder_DESEQ_org.rds")
Snyder_DESEQ_matrix <- readRDS("./Snyder_DESEQ.rds")

head(Snyder_DESEQ_matrix)
head(Snyder_DESEQ_ORG_matrix)
```


ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}

C1_df = msigdbr(species = "Mus musculus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Mus musculus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Mus musculus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Mus musculus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Mus musculus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Mus musculus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Mus musculus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df)

list_of_gmt_files <- ODIS::convert_msigdbr_obj_to_gmt_file(list_of_sets)
```


GSEA
```{r}

snyder_outputs <- list()

for(Y in list(list("Snyder_All" = Snyder_DESEQ_matrix),
              list("Snyder_Org" = Snyder_DESEQ_ORG_matrix))
){
  X = Y[[1]]
  p <- X$deseq2
  fc <- X$log2FoldChange      
  entrezid <- X$ENTREZID
  
  snyder_gene_list <- (1 - p) *sign(fc) 
  names(snyder_gene_list) <- as.character(entrezid)
  
  snyder_gene_list = sort(snyder_gene_list, decreasing = TRUE)
  snyder_gene_list = snyder_gene_list[!duplicated(names(snyder_gene_list))]
  head(snyder_gene_list, n = 5)
  
  for(i in list_of_gmt_files){
    print(i)
    res <- ODIS::ODISGSEA(gene_list = snyder_gene_list, theGoFile = i, pval = 0.05)
    snyder_outputs[[names(Y)]][[i]] <- res ## need to structure outputs correctly
  }
  snyder_outputs[[names(Y)]]$orig_matrix <- X[]  
}

summary(snyder_outputs)
summary(snyder_outputs$Snyder_Org)
summary(snyder_outputs$Snyder_Org$orig_matrix)
head(snyder_outputs$Snyder_Org$orig_matrix$deseq2)
```

GENE VS GENE SET HEATMAPS
```{r}
ODIS::ODIS.Heatmaps(snyder_outputs)
```
