---
title: "STAT3 Pipeline"
author: "Lucie Chrastecka"
date: "5/21/2021"
output: html_document
editor_options: ]
  chunk_output_type: console
---

LIBRARY
```{r}
#PACKAGES
library(msigdbr)
library(gplots)
library(ggplot2)
library(heatmap.plus)
library(RColorBrewer)
library(biomaRt)
library(wesanderson)
library(readr)
library(FactoMineR)
library(readr)
library(factoextra)
library(dplyr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(gridExtra)
library(DESeq2)
library(data.table)
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library(qusage)


```


DATA
```{r}

full_STAT3 <- readRDS("./my_readcounts.rds")
full_STAT3$ex <- as.matrix(full_STAT3$ex)
STAT3_readcounts <- full_STAT3$ex

row.names(STAT3_readcounts) <- full_STAT3$featInfo$ENSEMBL

```


MOUSE ENSEMBL TO MOUSE ENTREZ GENE CONVERSION + MGI SYMBOL
```{r}

# STAT3MouseGenes <- full_STAT3$featInfo$ENSEMBL
# tmp_STAT3 <- ODIS::Mouse2Human(STAT3MouseGenes)
# head(tmp_STAT3)
# tmp_STAT3 <- lapply(tmp_STAT3,as.character)
# summary(tmp_STAT3)
# head(tmp_STAT3)

full_STAT3$featInfo <- lapply(full_STAT3$featInfo, as.character)
summary(full_STAT3$featInfo)
head(full_STAT3$featInfo)
```


#DESEQ2 
```{r}

KRAS_KO <- readRDS("./KRAS_KO_MATRIX.rds")
STAT3_KO <- readRDS("./STAT3_KO_MATRIX.rds")
DBL_KO <- readRDS("./DBL_KO_MATRIX.rds")
DBL_vs_WT <- readRDS("./DBLVSWT_MATRIX.rds")

# KRAS_KOMouseGenes <- KRAS_KO$GeneID
# tmp_KK <- ODIS::Mouse2Human(KRAS_KOMouseGenes)
# head(tmp_KK)
# tmp_KK <- lapply(tmp_KK,as.character)
# summary(tmp_KK)
# head(tmp_KK)
# 
# KRAS_KO <- merge(KRAS_KO, tmp_KK)
# summary(full_STAT3$featInfo)
# head(full_STAT3$featInfo)



```





ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}

C1_df = msigdbr(species = "Mus musculus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Mus musculus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Mus musculus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Mus musculus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Mus musculus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Mus musculus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Mus musculus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df)

list_of_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)
```


GSEA
```{r}

snyder_outputs <- list()

for(Y in list(list("Snyder_All" = Snyder_DESEQ_matrix),
              list("Snyder_Org" = Snyder_DESEQ_ORG_matrix))
){
  X = Y[[1]]
  p <- X$deseq2
  fc <- X$log2FoldChange
  entrezid <- X$ENTREZID

  snyder_gene_list <- (1 - p) *sign(fc)
  names(snyder_gene_list) <- as.character(entrezid)

  snyder_gene_list = sort(snyder_gene_list, decreasing = TRUE)
  snyder_gene_list = snyder_gene_list[!duplicated(names(snyder_gene_list))]
  head(snyder_gene_list, n = 5)

  for(i in list_of_gmt_files){
    print(i)
    res <- GSEA(gene_list = snyder_gene_list, theGoFile = i, pval = 0.05)
    snyder_outputs[[names(Y)]][[i]] <- res ## need to structure outputs correctly
  }
  snyder_outputs[[names(Y)]]$orig_matrix <- X[]
}

summary(snyder_outputs)
summary(snyder_outputs$Snyder_Org)
summary(snyder_outputs$Snyder_Org$orig_matrix)
head(snyder_outputs$Snyder_Org$orig_matrix$deseq2)z
```

GENE VS GENE SET HEATMAPS
```{r}
GSEA_OUTPUTS <- readRDS("./KRAS_GSEA.rds")
ODIS.Heatmaps(GSEA_OUTPUTS) #gotta load pdist homie

#MAKE DF AND LOOP THROUGH gsea_output APPENT THIS TO BOTTOM OF DF
#MAKE LEADING EDGE HEATMAP

```
