---
title: "GSM_LLB_NMF_GSEA"
author: "Lucie Chrastecka"
date: '2022-06-01'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package Library
```{r}
library(BBmisc) #for normalize
library(msigdbr)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Rn.eg.db)

```

ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}
C1_df = msigdbr(species = "Rattus norvegicus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Rattus norvegicus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Rattus norvegicus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Rattus norvegicus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Rattus norvegicus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Rattus norvegicus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Rattus norvegicus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Rattus norvegicus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Rattus norvegicus", category = "C8", subcategory = "") #update on all
Hall_df = msigdbr(species = "Rattus norvegicus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df,
                    Hall = Hall_df)

list_of_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)
```

Normalize and make GSEA friendly "gene_list" from NMF Vectors
```{r}
 LLB_NMF <- readRDS("./LLB_NMF.rds")
 head(LLB_NMF)
 
 nmf_norm <- BBmisc::normalize(LLB_NMF, method = "range", range = c(0, 1), margin = 1L, on.constant = "quiet")
 head(nmf_norm)
 df1 <- nmf_norm[,1]
 head(df1)

```

Apply PatternMarker Transformation and make GSEA friendly "gene_list"
```{r}
LLB_NMF <- readRDS("./LLB_NMF.rds")
head(LLB_NMF)

nmf_pm <- transformedPM(LLB_NMF)
head(nmf_pm)

rank <- 3
nmf_tfpm <- (sqrt(rank-1)/2 - nmf_pm)^3
head(nmf_tfpm)
df2 <- nmf_tfpm[,1]
head(df2)
```


GSEA on all three vectors of NMF +orig values 
```{r}

#by dropping anything that is negatively enriched (bottom of the NMF vector) we do not consider as a hit. Therefore, we allow GESA  to focus only on the genes on the top of the NMF pile. 
 

LLB_NMF_GSEA_TFPM <- list()

## Both of the following lists have naming convention "v1","v2", etc, so you can index them in a single for loop by assigning the loop variable as the character string.

## Make list of norm aka raw scores
Q = list(V1 = nmf_norm[,1, drop = F],
         V2 = nmf_norm[,2, drop = F],
         V3 = nmf_norm[,3, drop = F])


## make list of tfpm scores.
new_y = list(V1 = nmf_tfpm[,1, drop = F],
             V2 = nmf_tfpm[,2, drop = F],
             V3 = nmf_tfpm[,3, drop = F])
    
    
for(Y in c("V1","V2","V3") #drop = f MEANS KEEP IT AS A MATRIX WITH COLLUMNS AND
){
  
  ## Make vector sorted gene list of TFPM scores
    X <- new_y[[Y]]
    gene_list = X[,1]
    gene_list = sort(gene_list, decreasing = TRUE)
    gene_list = gene_list[!duplicated(names(gene_list))]
    print("head gene_list")
    head(gene_list, n = 5)
    
    ## Make vector sorted gene list of raw nmf scores
    Z <- Q[[Y]]
    orig_value = Z[,1]
    orig_value = orig_value[!duplicated(names(orig_value))]
    orig_value <- orig_value[match(names(gene_list), names(orig_value))] #SORTED BASED ON GENE_LIST TO MAINTAIN ORDER
    print("head orig_value")
    head(orig_value, n = 5)
    
    head(names(gene_list),n=5)
    
    print(" Are these three things ^^ sorted the same way ??!?!?!?!?!?")
    
    
    for(i in list_of_gmt_files){
      print(i)
      res <- GSMGSEA(gene_list = gene_list, theGoFile = i, pval = 0.1, onlypos = TRUE) #drop to 0.1, onlypos is true because NMF
      LLB_NMF_GSEA_TFPM[[Y]][[i]] <- res  ## find a way to reference "nmf_norm" and "nmf_norm_org"
    }
    #orig_matrix must be a data frame
    LLB_NMF_GSEA_TFPM[[Y]]$orig_matrix <- as.data.frame(list(log2FoldChange = orig_value,
                                                                    EnrichmentScore = gene_list,
                                                                    ENTREZID = names(gene_list),
                                                                    SYMBOL = RatENT2RatSYM(names(gene_list)))) #rat conversion function returns some NA's 
    
}

#this^^ is out of order. orix matrix overwrites any collected GSEA reults and then a random data frame gets constructed from irrelevant garbage

summary(LLB_NMF_GSEA_TFPM)
summary(LLB_NMF_GSEA_TFPM$V1)
summary(LLB_NMF_GSEA_TFPM$V1$orig_matrix)
head(LLB_NMF_GSEA_TFPM$V3$`./myC1.gmt`$Results)
str(LLB_NMF_GSEA_TFPM$V2$orig_matrix$log2FoldChange)

saveRDS(LLB_NMF_GSEA_TFPM, "./LLB_NMF_GSEA_TFPM_NEW_0.1p.rds")

```