---
title: "GSM_Snyder_DESEQ2_GSEA.Rmd"
author: "Lucie Chrastecka"
date: "2/18/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

ALL MY SETS + CONVERSION OF LIST OF SETS INTO .GMT FILES
```{r}
C1_df = msigdbr(species = "Mus musculus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Mus musculus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Mus musculus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Mus musculus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Mus musculus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Mus musculus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Mus musculus", category = "C8", subcategory = "") 
Hall_df = msigdbr(species = "Mus musculus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df,
                    Hall = Hall_df)

list_of_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)
saveRDS(list_of_gmt_files, "./list_of_gmt_files.rds")
```

LOADING IN MATRIXES AND GMT LISTS
```{r}

Snyder_DESEQ_ORG_matrix <- readRDS("./Snyder_DESEQ_org.rds")
Snyder_DESEQ_matrix <- readRDS("./Snyder_DESEQ.rds")
list_of_gmt_files <- readRDS("./list_of_gmt_files.rds")

head(Snyder_DESEQ_matrix)
head(Snyder_DESEQ_ORG_matrix)
print(list_of_gmt_files)
```

GSEA For both all and organoid only 
```{r}

snyder_outputs <- list()

for(Y in list(list("Snyder_All" = Snyder_DESEQ_matrix),
              list("Snyder_Org" = Snyder_DESEQ_ORG_matrix))
){
  X = Y[[1]]
  p <- X$deseq2
  fc <- X$log2FoldChange      
  entrezid <- X$ENTREZID
  
  snyder_gene_list <- (1 - p) *sign(fc) 
  names(snyder_gene_list) <- as.character(entrezid)
  
  snyder_gene_list = sort(snyder_gene_list, decreasing = TRUE)
  snyder_gene_list = snyder_gene_list[!duplicated(names(snyder_gene_list))]
  head(snyder_gene_list, n = 5)
  
  for(i in list_of_gmt_files){
    print(i)
    res <- ODISGSEA(gene_list = snyder_gene_list, theGoFile = i, pval = 0.05)
    snyder_outputs[[names(Y)]][[i]] <- res ## need to structure outputs correctly
  }
  snyder_outputs[[names(Y)]]$orig_matrix <- X[]  
}

summary(snyder_outputs)
summary(snyder_outputs$Snyder_Org)
summary(snyder_outputs$Snyder_Org$orig_matrix)
head(snyder_outputs$Snyder_Org$orig_matrix$deseq2)

saveRDS(snyder_outputs, "./gsea_snyder_outputs.rds")
```