---
title: "ODIS_Snyder_NMF_CELL_GSEA"
author: "Lucie Chrastecka"
date: '2022-05-02'
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Package Library
```{r}
library(BBmisc) #for normalize
library(msigdbr)
```

ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}
C1_df = msigdbr(species = "Mus musculus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Mus musculus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Mus musculus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Mus musculus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Mus musculus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Mus musculus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Mus musculus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Mus musculus", category = "C8", subcategory = "") 
Hall_df = msigdbr(species = "Mus musculus", category = "H", subcategory = "")


list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df,
                    Hall = Hall_df)

list_of_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)
```

Make GSEA friendly "gene_list" from NMF Vectors
```{r}
Snyder_NMF_ORG <- readRDS("./Snyder_NMF_ORG.rds")
head(Snyder_NMF_ORG)

nmf_norm_org <- BBmisc::normalize(Snyder_NMF_ORG, method = "range", range = c(0, 1), margin = 1L, on.constant = "quiet")
head(nmf_norm_org)
df1 <- nmf_norm_org[,1]
head(df1)

```

Apply PatternMarker Transformation and make GSEA friendly "gene_list"
```{r}
Snyder_NMF_ORG <- readRDS("./Snyder_NMF_ORG.rds")
head(Snyder_NMF_ORG)

nmf_pm <- PatternMarker(Snyder_NMF_ORG)
head(nmf_pm)

rank <- 3
s_nmf_tfpm <- (sqrt(rank-1)/2 - nmf_pm)^3
head(s_nmf_tfpm)
df2 <- s_nmf_tfpm[,1]
head(df2)
```

Gsea on All three vectors of NMF_ORG
```{r}

snyder_nmfs_org <- list()

Q = list(V1 = nmf_norm_org[,1, drop = F],
         V2 = nmf_norm_org[,2, drop = F],
         V3 = nmf_norm_org[,3, drop = F])


## make list of tfpm scores.
new_y = list(V1 = s_nmf_tfpm[,1, drop = F],
             V2 = s_nmf_tfpm[,2, drop = F],
             V3 = s_nmf_tfpm[,3, drop = F])

for(Y in c("V1","V2","V3") #drop = f MEANS KEEP IT AS A MATRIX WITH COLLUMNS AND
){
  
  ## Make vector sorted gene list of TFPM scores
    X <- new_y[[Y]]
    gene_list = X[,1]
    gene_list = sort(gene_list, decreasing = TRUE)
    gene_list = gene_list[!duplicated(names(gene_list))]
    print("head gene_list")
    head(gene_list, n = 5)
    
    ## Make vector sorted gene list of raw nmf scores
    Z <- Q[[Y]]
    orig_value = Z[,1]
    orig_value = orig_value[!duplicated(names(orig_value))]
    orig_value <- orig_value[match(names(gene_list), names(orig_value))] #SORTED BASED ON GENE_LIST TO MAINTAIN ORDER
    print("head orig_value")
    head(orig_value, n = 5)
  
  for(i in list_of_gmt_files){
    print(i)
    res <- ODISGSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    snyder_nmfs_org[[Y]][[i]] <- res  ## find a way to reference "nmf_norm" and "nmf_norm_org"
  }
  #orig_matrix must be a data frame, added conversion function for ENT to SYM
  snyder_nmfs_org[[Y]]$orig_matrix <- as.data.frame(list(log2FoldChange = orig_value,
                                                         EnrichmentScore = gene_list,
                                                            ENTREZID = names(gene_list), 
                                                            SYMBOL = MouseENT2MouseSYM(names(gene_list)))) 
  
}

summary(snyder_nmfs_org)
summary(snyder_nmfs_org$V2)
summary(snyder_nmfs_org$V2$orig_matrix)
head(snyder_nmfs_org$V1$`./myC1.gmt`$Results)
str(snyder_nmfs_org$V2$orig_matrix$log2FoldChange)

saveRDS(snyder_nmfs_org, "./Snyder_NMF_ORG_GSEA_NEW.rds")
```