#' Modified GSEA function, this function performs fgsea on the results of previous Differential Expression analysis or filtering steps
#' @export
#' @import qusage
#' @import dplyr
#' @import gage
#' @import fgsea
#' @import ggplot2
#' @import gplots
#' @import tibble
#' @import stringr
#' @param gene_list is a named vector of scores where names must be entrezid's and scores a preffered number
#' @param theGoFile is a .gmt file name generated by convert_msigdbr_obj_to_gmt_file.R
#' @param pval is preferred cutoff for analysis
#' @return nothing
#' @examples 
#' res <- ODIS::ODISGSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)

ODISGSEA = function(gene_list, theGoFile, pval, verbose = TRUE, onlypos = FALSE) {
  set.seed(54321)
  library(dplyr)
  library(gage)
  library(fgsea)
  
  if ( any( duplicated(names(gene_list)) )  ) {
    warning("Duplicates in gene names")
    gene_list = gene_list[!duplicated(names(gene_list))]
  }
  if  ( !all( order(gene_list, decreasing = TRUE) == 1:length(gene_list)) ){
    warning("Gene list not sorted")
    gene_list = sort(gene_list, decreasing = TRUE)
  }
  myGO = fgsea::gmtPathways(theGoFile)
  if(verbose){
    print("printing myGO")
    print(head(myGO))
  }

  library(BiocParallel)
  #' fgsea takes pathways from theGoFile and places them into "myGO" -> a named list where each list is a vector of ENTREZ id's
  names(gene_list) <- as.character(names(gene_list))
  fgRes <- fgsea::fgseaMultilevel(pathways = myGO, 
                        stats = gene_list,
                        minSize=1,
                        maxSize=1000,
                        scoreType = c("std", "pos", "neg"),
                        gseaParam = 1,
                        nproc = 2
                        ) %>% 
    as.data.frame() 
  if(verbose){
    print("printing fgRes df")
    print(fgRes)
  }
  
  
  if (onlypos){
  fgRes <- fgRes %>% dplyr::filter(ES > 0)
  fgRes$padj <- p.adjust(p = fgRes$pval, method = "BH") #correction is less harsh, migh pick up more enriched gene sets (dropped anyting that goes in the neative direction by adding onlypos lfag)
  }
  
  fgRes <- fgRes %>% dplyr::filter(padj < !!pval)
  
  #fgRes is a dataframe of 9 VARIABLES
  
  if(verbose){
    print("printing str of fgRes")
    print(str(fgRes))
  }
  
  ## Filter FGSEA by using gage results. Must be significant and in same direction to keep 
  gaRes = gage::gage(gene_list, gsets=myGO, same.dir=TRUE, set.size =c(15,600))
  
  
  ups = as.data.frame(gaRes$greater) %>% 
    tibble::rownames_to_column("Pathway") %>% 
    dplyr::filter(!is.na(p.geomean) & q.val < pval ) %>%
    dplyr::select("Pathway")
  
  downs = as.data.frame(gaRes$less) %>% 
    tibble::rownames_to_column("Pathway") %>% 
    dplyr::filter(!is.na(p.geomean) & q.val < pval ) %>%
    dplyr::select("Pathway")
  
  #print(dim(rbind(ups,downs)))
  # keepups = fgRes[fgRes$NES > 0 & !is.na(match(fgRes$pathway, ups$Pathway)), ]
  # keepdowns = fgRes[fgRes$NES < 0 & !is.na(match(fgRes$pathway, downs$Pathway)), ]
  
  ### Collapse redundant pathways
  #sourced most recent file and fixed locally (made new version of collapsePathways function)
  #Up = collapsePathwaysNew(fgRes, pathways = myGO, stats = gene_list,  nperm = 500, pval.threshold = 0.9)
  #own = collapsePathwaysNew(fgRes, myGO, gene_list,  nperm = 500, pval.threshold = 0.9) 
  
  Up = fgRes[fgRes$NES > 0,]
  Down = fgRes[fgRes$NES < 0,]
  if(verbose){
    print("printing Up")
    print(Up)
    print("printing Down")
    print(Down)
  }
    
  fgRes = fgRes %>% arrange(desc(NES))
  
  if(verbose){
    print("printing fgRes")
    print(fgRes)
  }
  
  
  fgRes$pathway = stringr::str_replace(fgRes$pathway, "GO_" , "")
  
  if(verbose){
    print("fgRes")
    print(fgRes)
  }
  
  
  fgRes$Enrichment = ifelse(fgRes$NES > 0, "Up-regulated", "Down-regulated")
  filtRes = rbind(head(fgRes, n = 10),
                  tail(fgRes, n = 10 ))
  
  if(verbose){
    print("printing filtRes")
    print(filtRes)
  }
  
  # g = ggplot(filtRes, aes(reorder(pathway, NES), NES)) +
  #   geom_segment( aes(reorder(pathway, NES), xend=pathway, y=0, yend=NES)) +
  #   geom_point( size=5, aes( fill = Enrichment),
  #               shape=21, stroke=2) +
  #   scale_fill_manual(values = c("Down-regulated" = "dodgerblue",
  #                                "Up-regulated" = "firebrick") ) +
  #   coord_flip() +
  #   labs(x="Pathway", y="Normalized Enrichment Score",
  #        title="GSEA - Biological Processes") + 
  #   theme_minimal()
  # 
  # print("printing g")
  # print(g)
  
  
  output = list("Results" = fgRes) #, "Plot" = g)
  
  return(output)
  
}
