---
title: "ODIS_LLB_NMF_GSEA"
author: "Lucie Chrastecka"
date: '2022-06-01'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package Library
```{r}
library(BBmisc) #for normalize
library(msigdbr)
library(clusterProfiler)

```

ALL MY SETS + CONVERSION OF LIST OF SENTS INTO .GMT FILES
```{r}
C1_df = msigdbr(species = "Rattus norvegicus", category = "C1", subcategory = "")
C2_df = msigdbr(species = "Rattus norvegicus", category = "C2", subcategory = "CGP")
C2KEGG_df = msigdbr(species = "Rattus norvegicus", category = "C2", subcategory = "CP:KEGG")
C3_df = msigdbr(species = "Rattus norvegicus", category = "C3", subcategory = "MIR:MIRDB")
C4_df = msigdbr(species = "Rattus norvegicus", category = "C4", subcategory = "CGN")
C5_df = msigdbr(species = "Rattus norvegicus", category = "C5", subcategory = "BP")
C6_df = msigdbr(species = "Rattus norvegicus", category = "C6", subcategory = "")
C7_df = msigdbr(species = "Rattus norvegicus", category = "C7", subcategory = "IMMUNESIGDB")
C8_df = msigdbr(species = "Rattus norvegicus", category = "C8", subcategory = "") #update on all
Hall_df = msigdbr(species = "Rattus norvegicus", category = "H", subcategory = "")

list_of_sets = list(C1 = C1_df,
                    C2 = C2_df,
                    C2_KEGG = C2KEGG_df,
                    C3 = C3_df,
                    C4 = C4_df,
                    C5 = C5_df,
                    C6 = C6_df,
                    C7 = C7_df,
                    C8 = C8_df,
                    Hall = Hall_df)

list_of_gmt_files <- convert_msigdbr_obj_to_gmt_file(list_of_sets)
```

Make GSEA friendly "gene_list" from NMF Vectors
```{r}
LLB_NMF <- readRDS("./LLB_NMF.rds")
head(LLB_NMF)

nmf_norm <- BBmisc::normalize(LLB_NMF, method = "range", range = c(0, 1), margin = 1L, on.constant = "quiet")
head(nmf_norm)
df1 <- nmf_norm[,1]
head(df1)

```

GSEA on all three vectors of NMF
```{r}

LLB_NMF_GSEA <- list()

for(Y in list(list("V1" = nmf_norm[,1, drop = F]),
              list("V2" = nmf_norm[,2, drop = F]),
              list("V3" = nmf_norm[,3, drop = F])) #drop = f MEANS KEEP IT AS A MATRIX WITH COLLUMNS AND 
){
  X <- Y[[1]]
  
  gene_list = X[,1]
  gene_list = sort(gene_list, decreasing = TRUE)
  gene_list = gene_list[!duplicated(names(gene_list))]
  head(gene_list, n = 5)
  

  
  for(i in list_of_gmt_files){
    print(i)
    res <- ODISGSEA(gene_list = gene_list, theGoFile = i, pval = 0.05)
    LLB_NMF_GSEA[[names(Y)]][[i]] <- res  ## find a way to reference "nmf_norm" and "nmf_norm_org"
  }
  #orig_matrix must be a data frame
  LLB_NMF_GSEA[[names(Y)]]$orig_matrix <- as.data.frame(list(log2FoldChange = gene_list,
                                                            ENTREZID = row.names(X),
                                                            SYMBOL = RatENT2RatSYM(row.names(X)))) #rat conversion function returns some NA's 
  
}

summary(LLB_NMF_GSEA)
summary(LLB_NMF_GSEA$V1)
summary(LLB_NMF_GSEA$V1$orig_matrix)
head(LLB_NMF_GSEA$V2$`./myC1.gmt`$Results)
str(LLB_NMF_GSEA$V2$orig_matrix$log2FoldChange)

saveRDS(LLB_NMF_GSEA, "./LLB_NMF_GSEA_SYM.rds")

```